//file:noinspection GroovyAssignabilityCheck
rootProject.name = 'asm-ext'
//needs for EntryPoint
include "dev-annotations"

include("transformation:core")

include "analytics:method-return"
include "analytics:object-creation"


include "util:visitor"
include "util:method"
include "util:loader"
include "util:compile"
include "util:post-visitor"
include "util:node"
include "util:classfile-metadata"

