//file:noinspection GroovyAssignabilityCheck
rootProject.name = 'asm-ext'
//needs for EntryPoint
include "dev-annotations"

include "transformation:core"

include "analytics:method-return"
include "analytics:object-creation"
include "analytics:dataflow-analyzer"
include "analytics:plugable-analyzer"
include "analytics:controlflow"
include "analytics:sequence"

include("postprocessors:plugin"+"")
include("postprocessors:dynamic-dispatch1")


include "util:visitor"
include "util:method"
include "util:loader"
include "util:compile"
include "util:post-visitor"
include "util:node"
include "util:classfile-metadata"
include "util:dynamic-dispatch"
include "util:insn-print"

include "tools:method-graph"

def scriptPath = getClass().protectionDomain.codeSource.location.path
if(new File(new File(scriptPath),"sandbox")){
    include("sand"+"box")
}