//noinspection GroovyAssignabilityCheck
sourceSets.main.java.srcDirs = ["src/java", "$buildDir/generated/sources/annotationProcessor/java/main", "generated/"]
sourceSets.main.resources.srcDirs = ["src/resources"]
//noinspection GroovyAssignabilityCheck
sourceSets.test.java.srcDirs = ["test/java"]
sourceSets.test.resources.srcDirs = ["test/resources"]

dependencies {
    testImplementation platform("org.junit:junit-bom:$junitVersion")
    testImplementation 'org.junit.jupiter:junit-jupiter'

//    api(aproj("util:loader"))
    api(project(":util:insn-print"))
    api(project(":analytics:plugable-analyzer"))
    testImplementation(project(":util:loader"))


//    implementation "org.ow2.asm:asm-util:$asmVersion"
//    implementation "org.ow2.asm:asm-tree:$asmVersion"
//    implementation "org.ow2.asm:asm-analysis:$asmVersion"

    compileOnly "org.jetbrains:annotations:$jetbrainsAnnoVersion"
}

test {
    useJUnitPlatform()
}

